package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTypefaceConfig;
import org.linlinjava.litemall.db.domain.LitemallTypefaceConfigExample;

public interface LitemallTypefaceConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    long countByExample(LitemallTypefaceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTypefaceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    int insert(LitemallTypefaceConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTypefaceConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    LitemallTypefaceConfig selectOneByExample(LitemallTypefaceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    LitemallTypefaceConfig selectOneByExampleSelective(@Param("example") LitemallTypefaceConfigExample example, @Param("selective") LitemallTypefaceConfig.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    LitemallTypefaceConfig selectOneByExampleWithBLOBs(LitemallTypefaceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    List<LitemallTypefaceConfig> selectByExampleSelective(@Param("example") LitemallTypefaceConfigExample example, @Param("selective") LitemallTypefaceConfig.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    List<LitemallTypefaceConfig> selectByExampleWithBLOBs(LitemallTypefaceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    List<LitemallTypefaceConfig> selectByExample(LitemallTypefaceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    LitemallTypefaceConfig selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTypefaceConfig.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    LitemallTypefaceConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    LitemallTypefaceConfig selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTypefaceConfig record, @Param("example") LitemallTypefaceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallTypefaceConfig record, @Param("example") LitemallTypefaceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTypefaceConfig record, @Param("example") LitemallTypefaceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTypefaceConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallTypefaceConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTypefaceConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallTypefaceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_typeface_config
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}