package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallResource;
import org.linlinjava.litemall.db.domain.LitemallResourceExample;

public interface LitemallResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    long countByExample(LitemallResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    int insert(LitemallResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    int insertSelective(LitemallResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    LitemallResource selectOneByExample(LitemallResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    LitemallResource selectOneByExampleSelective(@Param("example") LitemallResourceExample example, @Param("selective") LitemallResource.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    List<LitemallResource> selectByExampleSelective(@Param("example") LitemallResourceExample example, @Param("selective") LitemallResource.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    List<LitemallResource> selectByExample(LitemallResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    LitemallResource selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallResource.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    LitemallResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    LitemallResource selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallResource record, @Param("example") LitemallResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallResource record, @Param("example") LitemallResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_resource
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}