package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTransaction;
import org.linlinjava.litemall.db.domain.LitemallTransactionExample;

public interface LitemallTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    long countByExample(LitemallTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    int insert(LitemallTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    LitemallTransaction selectOneByExample(LitemallTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    LitemallTransaction selectOneByExampleSelective(@Param("example") LitemallTransactionExample example, @Param("selective") LitemallTransaction.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    List<LitemallTransaction> selectByExampleSelective(@Param("example") LitemallTransactionExample example, @Param("selective") LitemallTransaction.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    List<LitemallTransaction> selectByExample(LitemallTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    LitemallTransaction selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTransaction.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    LitemallTransaction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    LitemallTransaction selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTransaction record, @Param("example") LitemallTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTransaction record, @Param("example") LitemallTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_transaction
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}