package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTrace;
import org.linlinjava.litemall.db.domain.LitemallTraceExample;

public interface LitemallTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    long countByExample(LitemallTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    int insert(LitemallTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    LitemallTrace selectOneByExample(LitemallTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    LitemallTrace selectOneByExampleSelective(@Param("example") LitemallTraceExample example, @Param("selective") LitemallTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    List<LitemallTrace> selectByExampleSelective(@Param("example") LitemallTraceExample example, @Param("selective") LitemallTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    List<LitemallTrace> selectByExample(LitemallTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    LitemallTrace selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    LitemallTrace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    LitemallTrace selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTrace record, @Param("example") LitemallTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTrace record, @Param("example") LitemallTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trace
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}